### ISSUE TITLE
Browser extension does not refresh on URL change / page reload

### ISSUE THREAD

**Issue by mandymu** [sonatype-nexus-community/sonatype-platform-browser-extension#97] opened 2023-10-11 21:21 UTC
**Describe the bug**
When the user navigates a new component on npm, the browser extension doesn't refresh until it finishes loading information on all the versions of the previous component evaluation. 

**To Reproduce**
1. Open a component page say 'log4js'
2. Click on the Sonatype extension to see the info tab versions 
3. While the spinner is still loading the versions, navigate to another component say 'lodash'
4. The Chrome plugin keeps loading versions and shows information about the last component 'log4js'. 
5. Reloading the page, disabling and re-enabling the plugin doesn't help and it still shows 'log4js'

**Expected behavior**
The browser extension terminates the last evaluation and initiates a new evaluation on URL change/page reload.  

**Screenshots**
![Screenshot 2023-10-11 at 5 09 14 PM](https://github.com/sonatype-nexus-community/sonatype-platform-browser-extension/assets/6529545/1de261d7-7bd1-4bdc-a5d7-d8aae87a3bc9)

**Desktop information:**
OS: MacOS 13.5.1 
Browser Chrome
Version 117.0.5938.149 (Official Build) (x86_64)

**Comment by madpah** [comment] 2023-10-12 07:36
Hi @mandymu - thanks for the report.

Unfortunately, we've been unable to reproduce this behaviour as described. Are you able to share (internally) a video of the behaviour please?

Thanks

**Comment by madpah** [comment] 2023-10-18 10:32
The issue reported by @mandymu was confirmed as being caused by miss configuration of the Sonatype IQ Server in this example - the Base URL was not set.

Closing.

**Closed by madpah** 2023-10-18 10:32 UTC
Labels: triage-required
